SELECT ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_DATE,
    REQUIRED_DATE,
    SHIPPED_DATE,
    ESTIMATED_DELIVERY_DELAY,
    SHIPPING_DELAY,
    STORE_ID ,
    STAFF_ID,

    UNIQUE_ORDER_ITEM_ID,
    PRODUCT_ID,
	ORDER_ITEM_QUANTITY ,
	ORDER_ITEM_AMOUNT,

    CUSTOMER_NAME,
    CUSTOMER_STREET,
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    CUSTOMER_ZIP_CODE,

    STAFF_MANAGER_ID,
    STORE_NAME,
    STORE_STREET,
    STORE_CITY,
    STORE_STATE,
    STORE_ZIP_CODE,

    PRODUCT_NAME,
    CATEGORY_ID,
    CATEGORY_NAME,
    BRAND_ID,
    BRAND_NAME,
    MODEL_YEAR

FROM {{ ref('int_sales_production_data') }}
