SELECT ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_DATE,
    REQUIRED_DATE,
    SHIPPED_DATE,
    (AVG(ESTIMATED_DELIVERY_DELAY)) AS ESTIMATED_DELIVERY_DELAY,
    (AVG(SHIPPING_DELAY)) AS SHIPPING_DELAY,
	STRING_AGG( CAST(CATEGORY_NAME as STRING), ' + ') AS CATEGORY_ORDERED,
	STRING_AGG(CAST(BRAND_NAME as STRING), ' + ') AS BRAND_ORDERED,
	STRING_AGG(CAST(MODEL_YEAR as STRING), ' + ') AS MODEL_ORDERED,
    STORE_ID ,
    STAFF_ID,

	SUM(ORDER_ITEM_QUANTITY) AS TOTAL_ORDER_ITEM_QUANTITY ,
	ROUND(SUM(ORDER_ITEM_AMOUNT),1) AS TOTAL_ORDER_ITEM_AMOUNT,
	ROUND(AVG(ORDER_ITEM_QUANTITY),1) AS AVERAGE_ORDER_ITEM_QUANTITY ,
	ROUND(AVG(ORDER_ITEM_AMOUNT),1) AS AVERAGE_ORDER_ITEM_AMOUNT,

    CUSTOMER_NAME,
    CUSTOMER_STREET,
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    CUSTOMER_ZIP_CODE,

    STAFF_MANAGER_ID,
    STORE_NAME,
    STORE_STREET,
    STORE_CITY,
    STORE_STATE,
    STORE_ZIP_CODE


FROM {{ ref('mrt_daily_sales_production_data') }}

GROUP BY ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_DATE,
    REQUIRED_DATE,
    SHIPPED_DATE,
    STORE_ID ,
    STAFF_ID,
	
    CUSTOMER_NAME,
    CUSTOMER_STREET,
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    CUSTOMER_ZIP_CODE,

    STAFF_MANAGER_ID,
    STORE_NAME,
    STORE_STREET,
    STORE_CITY,
    STORE_STATE,
    STORE_ZIP_CODE