SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_DATE,
    REQUIRED_DATE,
    SAFE.PARSE_DATE('%Y-%m-%d', SHIPPED_DATE) as SHIPPED_DATE,
    DATE_DIFF(REQUIRED_DATE,ORDER_DATE,DAY) AS ESTIMATED_DELIVERY_DELAY,
    DATE_DIFF(SAFE.PARSE_DATE('%Y-%m-%d', SHIPPED_DATE),ORDER_DATE,DAY) AS SHIPPING_DELAY,
    STORE_ID ,
    STAFF_ID
FROM {{source("localbike_dataset",'orders')}}