SELECT
    ORDER_ID,
    ITEM_ID,
    CONCAT(ORDER_ID,'_',ITEM_ID) AS UNIQUE_ORDER_ITEM_ID,
    PRODUCT_ID ,
    QUANTITY AS PRODUCT_QUANTITY,
    LIST_PRICE AS PRODUCT_UNIT_PRICE,
    DISCOUNT,
   (ROUND((LIST_PRICE * (1-DISCOUNT)),2)* QUANTITY) AS DICSOUNTED_PRICE,    
FROM {{source ('localbike_dataset','order_items')  }}
    