SELECT STORE_ID,
    UPPER(STORE_NAME) AS STORE_NAME,
    UPPER(STREET) AS STORE_STREET,
    UPPER(CITY) AS STORE_CITY,
    `STATE` AS STORE_STATE,
    ZIP_CODE AS STORE_ZIP_CODE
FROM {{source ('localbike_dataset','stores')  }}